#!/usr/bin/env bash
#installs nginx and configure it to listen on port 80
#print "Hello World"

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx
service nginx start
sudo ufw 'Nginx HTTP'
sud nginx -t
sudo service nginx reload

sudo mkdir /var/www/html

echo 'Hello World!' > /var/www/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
