#!/usr/bin/env bash
# customizing a 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | /var/www/html/index.html



#creating a 404 error page
echo "ceci n'est pas une page" | sudo tee /var/www/html/404.html
#copy pasting from the error_page

string_for_replacement="listen 80 default_server;\\n\\terror_page 404 /404.html;\\n\\tlocation = /404.html {\\n\\t\\troot /var/html;\\n\\t\\tinternal;\\n\\t}"

sudo sed -i "s|listen 80 default_server;|$string_for_replacement|" /etc/nginx/sites-enabled/default

#restart nginx after implementing changes
sudo service nginx restart
