#!/usr/bin/env bash
# Installs HAProxy version with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo "frontend ogetatonny.com.ng
        bind 0:80
        default_backend ogetatony.com.ng_backend

backend ogetatony.com.ng_backend
        balance roundrobin
        server hostname hostIP:PORT check
        server 97266-web-01 54.236.12.190 check
        server 97266-web-02 54.90.17.84 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
