#!/usr/bin/env bash
# Installs HAProxy version with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo "frontend ogetadom.tech.ng
    bind 0:80
    default_backend ogetadom.tech.ng_backend

backend ogetadom.tech.ng_backend
    balance roundrobin
    server 97266-web-01 54.236.12.190
    server 97266-web-02 54.90.17.84
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
#checking for syntax errors

haproxy -c -f /etc/haproxy/haproxy.cf

# restarting haproxy

sudo systemctl restart haproxy
